### ISSUE TITLE
About License

### ISSUE THREAD

**Issue by 34j** [nakano000/Resolve_Script#1]
I think this is a wonderful tool. Respectfully, could you please set up a license so that others can use this tool? 
素晴らしいツールだと思います。よろしければ、他人が使えるようにライセンスを設定して頂けますか？ 
[Choose an open source license \| Choose a License](https://choosealicense.com/)

**Comment by nakano000** [comment]
ご意見ありがとうございます。
MIT License にしました。

**Comment by 34j** [comment]
ありがとうございます！
