### ISSUE TITLE
Request to add RTL in Copy Tool

### ISSUE THREAD

**Issue by niskala5570** [nakano000/Resolve_Script#15]
Thanks for this amazing script!
Just playing it a bit, is there a reason why there's no RtoL option?

![image](https://github.com/nakano000/Resolve_Script/assets/34799053/25fe7789-bcc2-44a2-a08a-afd40d5ca50f)

**Comment by nakano000** [comment]
I will add it if you wish.

**Comment by niskala5570** [comment]
> I will add it if you wish.

Please do, thank you so much  (⁠ﾉ⁠◕⁠ヮ⁠◕⁠)⁠ﾉ⁠*⁠.⁠✧

**Comment by nakano000** [comment]
Added in 2.5.11

**Comment by niskala5570** [comment]
Tested and worked fine, thank you so much!
