### ISSUE TITLE
MakeMacro: 立ち絵のポーズグループに初期数以上の項目を含めた時の現象

### ISSUE THREAD

**Issue by sivaDog** [nakano000/Resolve_Script#4]
大変便利なスクリプトを開発していただき、感謝しています． 
今回は「クラッシュするわけじゃないけど、気になる要素だな」という，思いでこちらに書かせていただきました．  
## 問題
MakeMacroで作成した立ち絵テンプレートのポーズページでの現象です  
マクロを作成するときにグループの元項目以上に要素を指定すると、作成したテンプレートではグループを折りたたむ時に、正常に折りたためない現象が発生しました   

下記の図は，[とある立ち絵](https://seiga.nicovideo.jp/seiga/im7736161)の`背後`グループに`root`グループから表示/非表示を持ってきたときの動作です．  
![タイトルなし](https://github.com/nakano000/Resolve_Script/assets/111517713/6d1cac40-8f09-443f-a8a7-2349d6ccec13)

## 対策
立ち絵の.settingファイル該当グループ項目で，`LBLC_NumInputs`の数を合わせる．

**Comment by sivaDog** [comment]
## 環境
Windows 11
DaVinci Resolve 18.1.4 Build 9
りぞりぷと 2.2.6

**Comment by nakano000** [comment]
ご意見ありがとうございます。

この問題はFusionの仕様が原因です。

ただ昔からの仕様なので対処法も確立されていて、
まず、Edit Controlで以下のようなLabelControlを作ります。

Name 背後
ID New_Haigo(被っていなければ何でもOK)
Show Arrowをチェック
Hide Next # 5

その後、マクロを作るときに、元の物ではなく新しく作ったLabelControlを使うようにします。

今回は元のLabelControlもUserControlsですので、LBLC_NumInputsの値を書き換えてもよいのですが、
後でマクロ内のノードの値を編集するときに見にくくなる場合があります。

**Comment by sivaDog** [comment]
Fusionの仕様が問題でしたか

新しくラベルコントロールを作成して対応しました！
ありがとうございます
