### ISSUE TITLE
[VoiceDropper]パワービンに間違って配置される

### ISSUE THREAD

**Issue by sivaDog** [nakano000/Resolve_Script#5]
素晴らしいスクリプトの作成、ありがとうございます  
VoiceDropperで意図しない動作が確認できたので報告させていただきます  

1. voicedropperを立ち上げる
2. パワービンからタイムラインに何かを持ってくる作業を行う
3. voicedropperが音声を検出した場合すべてパワービンのほうに音声データを追加してしまう  

また、パワービンに音声を保存してしまうため、プロジェクトを開きなおしたタイミングで音声ファイルのリンク切れが起きる

## 環境
windows 11
りぞりぷと 2.3.2
Davinci resolve 18.5

**Comment by nakano000** [comment]
ご報告ありがとうございます。

パワービンに配置される動作を確認しました。
ただ、現状のapiでは回避出来ない動作なので、
ブラックマジックのサポートに問い合わせてみます。

**Comment by nakano000** [comment]
この件の回避方法に関して
ブラックマジックのサポートより返答がありました。

要約すると時期未定で将来アップデート予定なので
アップデートを待ってください、とのことです。
