### ISSUE TITLE
Subtitles2Text+ implementation on macOS - macOSでのSubtitles2Text+の実装

### ISSUE THREAD

**Issue by quangmng** [nakano000/Resolve_Script#6]
Hi there! I'm opening this issue as a continuation of the macOS install. Thank you for your work on the macOS compatibility!
こんにちは、macOSインストールの続きとしてこの問題を開きます。macOSとの互換性についてのご尽力に感謝します！

Anyway, I noticed there are components within the 2.4.1 version containing Subtitles2Text+. 
とにかく、2.4.1バージョンの中にSubtitles2Text+を含むコンポーネントがあることに気づきました。

<img width="1032" alt="Screenshot 2023-09-18 at 13 06 53" src="https://github.com/nakano000/Resolve_Script/assets/57740309/4bf5d785-0703-4c4f-a62e-cc3c72f07c76">

However, when I started installing your script via Resolve Launcher and opened Resolve via Launcher, those components were not present like in the Windows version.
しかし、Resolve Launcher経由でスクリプトのインストールを開始し、Launcher経由でResolveを開いたところ、Windows版のようにこれらのコンポーネントが存在しませんでした。

<img width="666" alt="Screenshot 2023-09-18 at 13 04 08" src="https://github.com/nakano000/Resolve_Script/assets/57740309/acbcfd08-1382-4211-8d1a-16846582cff1">

---//---
Environment - 環境
macOS Ventura 13.5.2
DaVinci Resolve Studio 18.5
Resolve_Script 2.4.1 alpha

**Comment by nakano000** [comment]
pythonがdavinci resolveに認識されていないようです。
Resolve_Script2.4.2_mac_ALPHA2を使ってください。

・pythonをインストール(ツールは3.10.11で確認しています)
・setup_python.commandを実行
・りぞりぷと.commandを実行

**Comment by quangmng** [comment]
Apologies for the delay in replying - My university schedule has been quite busy recently, so I could not get back to you instantly. :(
返信が遅れて申し訳ない。最近、大学のスケジュールがかなり忙しくて、すぐに返信できなかったんだ。
--##--
Anyway, the script is working now! The script has been loaded into DaVinci successfully and is running similarly to the Windows implementation.
とにかく、スクリプトは動くようになった！スクリプトは無事にDaVinciに読み込まれ、Windowsの実装と同様に実行される。
<img width="605" alt="Screenshot 2023-10-04 at 14 40 56" src="https://github.com/nakano000/Resolve_Script/assets/57740309/2a59d7e7-de23-4c9e-a481-da15c8ecfbe9">
<img width="620" alt="Screenshot 2023-10-04 at 14 47 09" src="https://github.com/nakano000/Resolve_Script/assets/57740309/d0831538-0c89-4aea-ab95-e7606a39555a">
--##--
Thank you for implementing macOS support & for helping me resolve the issue! 
macOSのサポートを導入し、問題を解決してくれてありがとう！
(env: Resolve_Script2.4.2_mac_ALPHA2 @ DaVinci 18.5 & 18.6 - macOS Sonoma 14.0)

**Comment by nakano000** [comment]
Have a fun time
