### ISSUE TITLE
Davince Resolveが起動しなくなる

### ISSUE THREAD

**Issue by senapoyonne** [nakano000/Resolve_Script#7]
https://www.youtube.com/watch?v=SALo91ZO3SI
こちら動画を参考に立ち絵のセッティングをしていたところアプリがクラッシュ、その後再インストール、再起動をしてもきどうしなくなりました。
思い当たりそうな原因といえば、スプリット済みの立ち絵のPATHを設定する際に立ち絵の画像を読み込まなかったので何度かスプリット済みの立ち絵のディレクトリを移動したくらいでしょうか。
他に必要な情報とうありましたらお願いします。

**Comment by nakano000** [comment]
ありがとうございます。
今度チュートリアルを作るときに、注意点として入れておきます。
